export const CARD_CONFIG: CardConfig[][] = [
    [
        {
            question: 'types of\nnuts',
            answers: [
                'Almonds',
                'Walnuts',
                'Cashews',
                'Pecans',
                'Hazelnuts',
                'Pistachios',
                'Macadamias',
                'Brazils',
                'Peanuts',
                'Chestnuts',
                'Acorns',
                'Hickories',
                'Barukas',
                'Filberts',
                'Coconuts',
                'Candlenuts',
                'Beechnuts',
                'Marconas',
                'Pine nuts',
                'Pignolias',
            ],
        },

        {
            question: 'birds',
            answers: [
                'Eagle',
                'Robin',
                'Cardinal',
                'Bluejay',
                'Dove',
                'Hawk',
                'Chickadee',
                'Goldfinch',
                'Heron',
                'Falcon',
                'Raven',
                'Bluebird',
                'Hummingbird',
                'Sparrow',
                'Barnowl',
                'Woodpecker',
                'Goose',
                'Mallard',
                'Snowyowl',
                'Kingfisher',
            ],
        },
        {
            question: 'common\nillness',
            answers: [
                'Cold',
                'Flu',
                'Strep',
                'Earache',
                'Sinusitis',
                'Bronchitis',
                'Pneumonia',
                'Gastritis',
                'UTI',
                'Pinkeye',
                'Allergies',
                'Asthma',
                'Migraine',
                'Eczema',
                'Hypertension',
                'Diabetes',
                'Depression',
                'Anxiety',
                'Arthritis',
                'COVID',
            ],
        },
    ],
    [
        {
            question: 'makes of\ncar',
            answers: [],
        },
        {
            question: 'food that\nare red',
            answers: [],
        },
        {
            question: 'planets',
            answers: [],
        },
    ],
    [
        {
            question: 'fruit juices',
            answers: [],
        },
        {
            question: 'super\nheroes',
            answers: [],
        },
        {
            question: 'cities in\nUSA',
            answers: [],
        },
    ],
];
